obs-websocket-community-projects/obs-websocket-js

- README.md
`obs-websocket-js` was used in `agdq17-layouts` to observe the active scene in OBS and change the behavior of the graphics accordingly. We also had a custom build of `obs-websocket` which could control our custom cropping plugin. Whenever we finished a run and hit "next run" on the schedule, `agdq17-layouts` would tell `obs-websocket` to reset the cropping.
> [Docs] Add agdq17-layouts to projects list

- README.md
- lib/OBSWebSocket.js
- lib/Socket.js
- lib/methodBinding.js
- lib/util/logAmbiguousError.js
- package.json
This gets rid of the `logLevel` dependency in favor of the [`debug`](https://github.com/visionmedia/debug) module. `debug` has a few advantages:
- Because `npm` does some degree of flattening, it's possible that multiple modules (or even the application which consumes `obs-websocket-js`) might end up with the same reference to a `logLevel` instance. This makes it impossible to silence `obs-websocket-js`'s log output without potentially interefering with the log output of other modules or applications running in the same Node.js context.
- `debug` provides a consistent, standardized method of configuration via environment variables.
Closes #32.
> Several fixes and refactors

- .eslintignore
- .gitignore
- lib/Socket.js
- package.json
- test/.eslintrc
- test/auth.spec.js
This adds bare minimum tests that ensure the ability to connect, authenticate, and realize when authentication has failed due to an incorrect password being provided.
I propose two options:
1) Merge this PR as-is just to get _some_ tests on `master`
2) Continue working on this PR until it's reached a level of coverage that we feel comfortable stopping at
My personal preference is to merge this PR right away so that other contributors can have a base to build from, and tests for other portions of code can come in as smaller PRs.
You'll also want to look into getting [Coveralls](https://coveralls.io/) set up.
> [Tests] Add basic connection & authentication tests

- lib/Socket.js
The rationale for this change is that it should probably always be safe for a user to call .disconnect, even if it won't do anything. They shouldn't need to check any state before doing so.
> [API] Fix errors caused when .disconnect is called at the wrong time

- .eslintignore
- Gruntfile.js
- README.md
- lib/OBSWebSocket.js
- lib/Socket.js
- lib/Status.js
- samples/node-sample/index.js
- samples/web-sample/obs-websocket-client.html
* Switch back from ws.on('open') to ws.onopen()
* Remove worthless Status.wrap method
* Fix incoming message parsing
**Related Issue (if applicable):**
none
**General Description:**
Since this doesn't package node's `ws` module, switching back to the base WebSocket onhandlers.
Also cleaned up some of the samples a bit.
> Fix webpack distributable

- .eslintignore
- .travis.yml
- .travis/update-api.js
- .travis/update-api.sh
- package.json
#61 
Figured generating after everything else would be fine since this will kick off another gh-pages update anyways. It'd be kind of confusing to have an updated gh-pages commit before the master was updated.
Used the built in https library because I didn't want to introduce another dev dependency.
> ci: Generate/update api at end of travis builds, Closes #61

- .travis.yml
- lib/Socket.js
- package.json
- test/auth.spec.js
- test/setup/util.js
n/a
`.on('error')` is listed as emitting unhandled socket errors and exceptions, but it wasn't.
Also fixed a sequencing issue I discovered during this where it wasn't marking the connection as `settled` until after `onConnectionXYZ` events were completed - meaning you could encounter socket issues during that time and have them be swallowed as if they were connection issues.
> api: Ensure `error` emits occur when unhandled Socket errors/messages are encountered

- .travis.yml
- test/auth.spec.js
- test/events.spec.js
- test/requests.spec.js
Currently, tests are run against the un-transformed source found in `lib`. This is potentially hazardous, because it is possible for tests to pass but for the published `npm` package to be broken, because the published package is a transformed output of these sources files.
This change ensures that we are always testing against whatever the `main` entrypoint defined in `package.json` is, which helps avoid this scenario where tests pass but the build might be broken.
> test: test actual build output

- .eslintignore
- .gitignore
- .travis/gh-pages.sh
- bower.json
- lib/index.js
- package.json
It is doubtful that there are many users of `obs-websocket-js` still using environments which are limited to ES5. This is a layer of abstraction that I believe we can safely remove.
BREAKING CHANGE: The es5 build has been removed. Users limited to es5 environments should continue using the latest 2.x release.
> chore: remove es5 build

- .travis.yml
The current `.travis.yml` specifies `ruby` as the target language. This wastes build time setting up a Ruby environment which is not needed.
> chore(build): speed up builds by specifying node as the target language

- .gitignore
- .npmrc
- package-lock.json
Our CI builds can randomly begin to fail due to dependencies updating out from under us unexpectedly. Committing our `package-lock.json` to git will help reduce this, by ensuring our CI builds use the exact dependencies we expect.
The CI build for this will fail until #152 is also merged, due to the types build script not currently working with `obs-websocket` 4.6.
Will merge in a day or so if there's no objections.
> chore(package): add package-lock.json

- .travis/build-types.ts
Without authentication, GitHub uses simple IP-based ratelimiting with an extremely low limit. This makes it effectively impossible to use on a CI platform such as Travis.
Authenticated requests get a far higher rate limit, and are not IP-based.
> build(travis): fix GitHub rate limiting

- .travis/build-types.ts
- webpack.config.js
#170 
The dist version can now be imported using static imports. Previously this was not working for me.
> Export using commonjs-module in webpack so it can be imported using static imports

- .travis.yml
Node 8 has left its maintenance window, and is now unuspported. This PR drops it, and adds Node 12 to our test matrix.
> test: drop node 8, add node 12

- package-lock.json
- package.json
The `test:ava` script was missing an extra `--`, meaning that the `--serial --timeout=10s` wasn't actually doing anything.
Instead of fixing this by adding that `--`, I figured it was best to update `ava` and leverage its expanded ability to be configured via a stanza in `package.json`. We already have this stanza, so making more use of it just made sense to me, rather than spreading our configuration between scripts and the stanza.
> test: fix ava config

- test/auth.spec.js
- test/events.spec.js
- test/requests.spec.js
- test/setup/environment.js
Constructors cannot be async, so putting an `await` in front of `new WebSocket.Server` does nothing. So, I removed it.
Since this was the only `await` present in `makeServer()`, I was able to remove the `async` from this method entirely. It does not seem to negatively impact the tests at all.
> test: remove useless await

- lib/Socket.js
This PR adds support for secure websockets. This is very useful when running obs-websocket behind a proxy like ngrok. This allows OBS to be controlled from HTTPS websites.
> Add support for secure websockets

- .travis/build-types.ts
N/A
This PR changes/fixes a few things in relation to the type build script:
- Fixes an issue where the build would fail because the `ScenesCollection` typedef wasn't defined yet.
- Adds an `error` event type with (mostly) correct types. This makes #217 redundant and is a little more specific as the type returned should be more than a string, as the underlying error is a normal WebSocket error.
- Fixes the `Output` typedef not being used correctly.
- Fixes all of the events/requests that use `Array<Object>` parameters to actually have correct types; before they seemed to only have the type of their last property as the array type (for example `string[]`).
- Adds a small "hack" to allow arbitrary properties for the new `ExecuteBatch` request; you could probably have really good types …
> Multiple type building improvements/fixes

- lib/OBSWebSocket.js
- lib/Status.js
#223 
This adds a simple check to the `send` function to make sure the supplied arguments parameter is *actually* an object (excluding arrays) and throws an error if not.
Added because of the referenced issue above where the author was able to supply an array, which the JavaScript somehow attempts to convert into a (broken) object, which gets sent without a `message-id`, and then the plugin returns an error message but because there is no `message-id` the `send` function gets stuck/hangs.
> Check that the send function's "args" parameter is actually an object

- src/types.ts
I had a type error with the "GetGroupItemList" request. After looking around, found out that it is  "GetGroupSceneItemList" for v5
reference: https://docs.google.com/spreadsheets/d/1LfCZrbT8e7cSaKo_TuPDd-CJiptL7RSuo8iE63vMmMs/edit#gid=1402923009
> Renaming GetGroupItemList to GetGroupSceneItemList

- README.md
None
The new default port is 4455 since 4444 is reserved for obs-websocket < 5.
Only a small documentation change.
> Update port numbers in readme

- scripts/build-types.ts
- src/types.ts
https://github.com/obs-websocket-community-projects/obs-websocket-js/pull/300
Currently the `generate:obs-types` NPM run script cannot be successfully run, because the latest release from `obs-websocket` maps to `tag_name` `4.9.1-compat` which is not a correct commit (and also not the latest non-deprecated version).
In this PR I add the ability to specify a custom commit that we can base the typings off of (using environment variable `GH_COMMIT`). Then I use commit `5716577019b1ccda01a12db2cba35a023082b7ad` which maps to version 5.0.2 in order to generate the updated typings.
Without the `GH_COMMIT` variable, the old behavior is kept so that later releases from `obs-websocket` will (hopefully) be automatically picked up.
> Updated typings from obs-websocket 5.0.2

- package.json
- src/base.ts
- tsconfig.json
With `"moduleResolution": "node16"` set, users of this library receives incorrect `OBSWebsocket` type because internally the `eventemitter3` import fails.
> fix: fix type error with moduleResolution node16

- src/base.ts
None that I'm aware of.
The debug library uses a slightly particular way of exporting a namespace. This causes an issue when mixing this library in a typescript module that uses `esModuleInterop = false`.
Since the debug library is only used in 1 file and shouldn't be used by a library user anyway the easiest fix is to not export the debug lib.
> fix: don't export debug

- .github/CONTRIBUTING.md
- src/types.ts
N/A
add: v5.5 of the OBS Websocket added request for SplitFileRecord and CreateRecordChapter and event type RecordFileChanged.
update: Contributing guide as the commands for test and lint changed. 
fix: Contributing guide markdown lint warnings for formatting.
> add: OBS Websocket v5.5 features
